### ISSUE TITLE
'os.stat_result' object has no attribute 'st_file_attributes'

### ISSUE THREAD

**Issue by dauptaia** [rahulbordoloi/Directory-Tree#10]
hello, its me again.

Since ver. 0.0.3 , I get everywhere the same Exception:
'os.stat_result' object has no attribute 'st_file_attributes'

My tests were with python 3.7 to 3.9.14 at least.

Il will stick to 0.0.2 in the meantime.

Thank you a lot!

**Comment by rahulbordoloi** [comment]
Hey @dauptaia, Thanks for Raising the Issue. By "I get everywhere" - Do you mean every time the Class/Method gets invoked? Can you please share the steps, OS to reproduce the same. Would be very much helpful.

**Comment by dauptaia** [comment]
Yes , each invocation. I got this on several MacOS and Unix machines.

Mine is MacOS 12.6.3 (CPU Intel) with Python  3.9.14 .

I can reproduce the pb with

`
from directory_tree import display_tree
print(display_tree("."))
`

Which gives this with 0.0.3

`
/
Exception Occurred! Failed to Generate Tree:: 'os.stat_result' object has no attribute 'st_file_attributes'
None`

Works fine if I go back to 0.0.2

**Comment by rahulbordoloi** [comment]
Hey @dauptaia,
Looking into it. As I don't have access to Unix (Mac), taking a bit time to solve for the same. Would Solution it out at earliest.

PS - The Same's working in Linux and Windows.

**Comment by rahulbordoloi** [comment]
Hey @dauptaia, 
I've done the needful. Can you please clone and check if the issue still persists and let me know? Post your confirmation would push into PyPI and resolve this issue.

**Comment by dauptaia** [comment]
Issue closed for me. Waiting for upload on Pypi :)

**Comment by rahulbordoloi** [comment]
Uploaded to [PyPi](https://pypi.org/project/directory-tree/)! Thanks for Raising the Issue. :D
