### ISSUE TITLE
Only directory not files like `tree -d` in bash

### ISSUE THREAD

**Issue by kikislater** [rahulbordoloi/Directory-Tree#15]
Is there a way to only display directory not files like `tree -d` in bash ? 
Could you please describe how to use pattern as well ?

**Comment by rahulbordoloi** [comment]
Hello @kikislate,

Thanks for reaching out! As of now there're no provisions to display only the directories. Would definitely add as a new feature.

For using patterns, you can take reference from here - https://github.com/rahulbordoloi/Directory-Tree/blob/7e97351ff0d02bfd8b6f574856cbe6411c375712/Test/v0_0_4_Test.py#L29

Let me know if there're any further questions, would take the feature request soon and update in this loop.

**Comment by kikislater** [comment]
Hi,

Thank you for your answer. Unfortunately patterns doesn't work for me. If I try with 
I was thinking about using a list like `["*.*"]` allows to not display files ;-)
Example: 
```
>>> display_tree("DroneMDT", max_depth=4, show_hidden=True, ignore_list=["*.py"])
DroneMDT/
├── __init__.py
├── __pycache__/
│   ├── check_images.cpython-310.pyc
│   ├── enriched_func.cpython-310.pyc
│   ├── exif_helper.cpython-310.pyc
│   ├── geoflow_helper.cpython-310.pyc
│   ├── meteo_helper.cpython-310.pyc
│   ├── process_webodm.cpython-310.pyc
│   ├── raster_helper.cpython-310.pyc
│   ├── read_metadata.cpython-310.pyc
│   ├── settings.cpython-310.pyc
│   ├── status_codes.cpython-310.pyc
│   ├── zenodo_helper.cpython-310.pyc
│   └── zip_helper.cpython-310.pyc
├── check_images.py
├── data_to_geoflow
├── data_to_geoflow.py
├── enriched_func.py
├── exif_helper.py
├── generate_drone_metadata.R
├── geoflow_helper.py
├── list_projects.py
├── list_users.py
├── main.py
├── metadata.txt
├── meteo_helper.py
├── prepare_upload.py
├── process_webodm.py
├── raster_helper.py
├── read_metadata.py
├── README.md
├── requirements.txt
├── settings.py
├── status_codes.py
├── uas_report_metrics.Rmd
├── Untitled.ipynb
├── upload_raw_to_zenodo.py
├── zenodo.json
├── zenodo_helper.py
├── zenodo_helper.py.old
├── zenodo_uploader.py
└── zip_helper.py
```


Btw for my orignal question, I ended with this function:

```
def tree_sort_by_name(path=os.getcwd(), indent=0):
    print(indent*' ' + '└─', path.split('/')[-1])
    treed = indent*' ' + '└─' +  path.split('/')[-1]
    for file in sorted(os.listdir(path)):
        if os.path.isdir(os.path.join(path, file)):
            treed = treed + "\n" + tree_sort_by_filename(os.path.join(path, file), indent+2)
        ### To print files as well
        # else:
            # print('  ' + indent*' ' + '└─', file)
    return treed
```

**Comment by rahulbordoloi** [comment]
Earlier - 
![image](https://github.com/user-attachments/assets/35fa6e73-6015-4699-b668-d29f73c7a77e)

Now (Conditional Parameterized) -
![image](https://github.com/user-attachments/assets/34e4ef54-e2c6-47c4-bc7d-dc157b40e320)

Is this what you were seeking for? 
Also, WIP for Bash Support.

**Comment by rahulbordoloi** [comment]
New Changes are Live in PyPi! (https://pypi.org/project/directory-tree/) @kikislater
