### ISSUE TITLE
[Request] Parameter to show files or directories first

### ISSUE THREAD

**Issue by AutonomousCat** [rahulbordoloi/Directory-Tree#17]
For my use case, it would make the output more readable to show files first. So before "utils/", "main.py" will show (for example).

**Comment by rahulbordoloi** [comment]
Earlier - 
![image](https://github.com/user-attachments/assets/843a1bb1-4e7c-4fe8-ad97-dc3213f908c3)

Now (Conditional Parameterized) - 
![image](https://github.com/user-attachments/assets/eab60c6c-9902-451b-81cb-4f0433321670)

Is this what you seeked for? @AutonomousCat

**Comment by rahulbordoloi** [comment]
New Changes are Live in PyPi! (https://pypi.org/project/directory-tree/) @AutonomousCat
