### ISSUE TITLE
function display tree

### ISSUE THREAD

**Issue by dauptaia** [rahulbordoloi/Directory-Tree#2]
the display tree() is sweet, but i would need only the string output -without the print to the std_out-, because I must redirect it in a GUI log.

Smthg like
(display_tree_as_str()) -> the string repr of the tree.
I can easily code it myself, but It would be nicer to add this simple feature to the API surface of your pckg 

Best regards

**Comment by dauptaia** [comment]
My current solution to make it clearer :

```python
# Importing Libraries
import os
from pathlib import Path
from directory_tree import directory_path

# Main Method


class DirectoryPath(directory_path):
    """Wrapper of the directory_path class 

    Only to get a camel case Named Class.
    Yes I know I am a pep008 b***tch
    but I did searched 30sec  where this directory_pathwas coming from
    """


def display_tree_as_str(dir_path=None):
    """return a display of the tree in a string

    By default, DIR_PATH is set to current working directory.
    """

    if dir_path is not None:
        dir_path = Path(dir_path)
    else:
        dir_path = Path(os.getcwd())

    out = str()
    paths = DirectoryPath.build_tree(dir_path)
    for path in paths:
        out += path.displayPath() + "\n"

    return out


if __name__ == '__main__':
    out = display_tree_as_str('.')
    print(out)
```

**Comment by rahulbordoloi** [comment]
@dauptaia, Hey Thanks for your Valuable Suggestions! I'll surely look into it towards the EOD or else you can put up a PR and I can merge it right straight away!

**Comment by rahulbordoloi** [comment]
@dauptaia Check #3. New Functionality has been added. :)

**Comment by dauptaia** [comment]
Works like a charm. Now a perfect fit for my needs. Thank you a lot!
