### ISSUE TITLE
Define tree depth

### ISSUE THREAD

**Issue by gustalima** [rahulbordoloi/Directory-Tree#4]
Hi, this library is really nice. I'm impressed by how fast I get the folder structure!

If I may, would be possible to define the depth of my search?

Best, 
Gustavo

**Comment by rahulbordoloi** [comment]
Hey @gustalima,

Thanks for your feedback, means a lot. :D 

And yes, you may define the depth of the search by yourself and create a PR for the same. Would be very much helpful.

**Comment by rahulbordoloi** [comment]
Issue Solved. Please check https://github.com/rahulbordoloi/Directory-Tree/pull/7 for Details. 

Code Available at Main Branch and [PYPI](https://pypi.org/project/directory-tree/0.0.3/).
